import React, { useEffect, useState } from 'react';
import Head from 'next/head'
import Navbar from '@components/Navbar';
import { Footer } from 'antd/lib/layout/layout';

export default function Home() {
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Navbar />
      </main>
      <Footer style={{ textAlign: 'center' }}>HIPPOS ©2022 Created by CDC - Team 3</Footer>
    </div>
  )
}
